// <auto-generated />
using System;
using ApiHortifruti;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiHortifruti.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiHortifruti.Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_compra");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int")
                        .HasColumnName("fornecedor_id");

                    b.Property<int>("MotivoMovimentacaoId")
                        .HasColumnType("int")
                        .HasColumnName("motivo_movimentacao_id");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_nota");

                    b.Property<decimal>("PrecoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FornecedorId" }, "fk_entrada_fornecedor1_idx");

                    b.HasIndex(new[] { "MotivoMovimentacaoId" }, "fk_entrada_motivo_movimentacao1_idx");

                    b.ToTable("entrada", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("CadastroPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cadastro_pessoa");

                    b.Property<DateOnly>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TelefoneExtra")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone_extra");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("fornecedor", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.FornecedorProduto", b =>
                {
                    b.Property<int>("FornecedorId")
                        .HasColumnType("int")
                        .HasColumnName("fornecedor_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<string>("CodigoFornecedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_fornecedor");

                    b.Property<DateOnly>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponibilidade");

                    b.HasKey("FornecedorId", "ProdutoId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "FornecedorId" }, "fk_fornecedor_has_produto_fornecedor_idx");

                    b.HasIndex(new[] { "ProdutoId" }, "fk_fornecedor_has_produto_produto1_idx");

                    b.ToTable("fornecedor_produto", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenciaBancaria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("agencia_bancaria");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("ContaBancaria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("conta_bancaria");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TelefoneExtra")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone_extra");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.HistoricoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataAlteracao")
                        .HasColumnType("date")
                        .HasColumnName("data_alteracao");

                    b.Property<decimal>("PrecoProduto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_produto");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProdutoId" }, "fk_historico_produto_produto1_idx");

                    b.ToTable("historico_produto", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.ItemEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntradaId")
                        .HasColumnType("int")
                        .HasColumnName("entrada_id");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lote");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Validade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("validade");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EntradaId" }, "fk_item_entrada_entrada1_idx");

                    b.HasIndex(new[] { "ProdutoId" }, "fk_item_entrada_produto1_idx");

                    b.ToTable("item_entrada", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.ItemSaida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaidaId")
                        .HasColumnType("int")
                        .HasColumnName("saida_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProdutoId" }, "fk_itens_saida_produto1_idx");

                    b.HasIndex(new[] { "SaidaId" }, "fk_itens_saida_saida1_idx");

                    b.ToTable("item_saida", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.MotivoMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("motivo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("motivo_movimentacao", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade_atual");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade_minima");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("int")
                        .HasColumnName("unidade_medida_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Codigo" }, "codigo_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "CategoriaId" }, "fk_produto_categoria1_idx");

                    b.HasIndex(new[] { "UnidadeMedidaId" }, "fk_produto_unidade_medida1_idx");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Saida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastroCliente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cadastro_cliente");

                    b.Property<DateOnly>("DataSaida")
                        .HasColumnType("date")
                        .HasColumnName("data_saida");

                    b.Property<bool>("Desconto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("desconto");

                    b.Property<TimeOnly>("HoraSaida")
                        .HasColumnType("time")
                        .HasColumnName("hora_saida");

                    b.Property<int>("MotivoMovimentacaoId")
                        .HasColumnType("int")
                        .HasColumnName("motivo_movimentacao_id");

                    b.Property<decimal?>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_final");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MotivoMovimentacaoId" }, "fk_saida_motivo_movimentacao1_idx");

                    b.ToTable("saida", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("abreviacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("unidade_medida", (string)null);
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Entrada", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Fornecedor", "Fornecedor")
                        .WithMany("Entrada")
                        .HasForeignKey("FornecedorId")
                        .IsRequired()
                        .HasConstraintName("fk_entrada_fornecedor1");

                    b.HasOne("ApiHortifruti.Domain.MotivoMovimentacao", "MotivoMovimentacao")
                        .WithMany("Entrada")
                        .HasForeignKey("MotivoMovimentacaoId")
                        .IsRequired()
                        .HasConstraintName("fk_entrada_motivo_movimentacao1");

                    b.Navigation("Fornecedor");

                    b.Navigation("MotivoMovimentacao");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.FornecedorProduto", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Fornecedor", "Fornecedor")
                        .WithMany("FornecedorProduto")
                        .HasForeignKey("FornecedorId")
                        .IsRequired()
                        .HasConstraintName("fk_fornecedor_has_produto_fornecedor");

                    b.HasOne("ApiHortifruti.Domain.Produto", "Produto")
                        .WithMany("FornecedorProduto")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("fk_fornecedor_has_produto_produto1");

                    b.Navigation("Fornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.HistoricoProduto", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Produto", "Produto")
                        .WithMany("HistoricoProduto")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("fk_historico_produto_produto1");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.ItemEntrada", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Entrada", "Entrada")
                        .WithMany("ItemEntrada")
                        .HasForeignKey("EntradaId")
                        .IsRequired()
                        .HasConstraintName("fk_item_entrada_entrada1");

                    b.HasOne("ApiHortifruti.Domain.Produto", "Produto")
                        .WithMany("ItemEntrada")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("fk_item_entrada_produto1");

                    b.Navigation("Entrada");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.ItemSaida", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Produto", "Produto")
                        .WithMany("ItemSaida")
                        .HasForeignKey("ProdutoId")
                        .IsRequired()
                        .HasConstraintName("fk_itens_saida_produto1");

                    b.HasOne("ApiHortifruti.Domain.Saida", "Saida")
                        .WithMany("ItemSaida")
                        .HasForeignKey("SaidaId")
                        .IsRequired()
                        .HasConstraintName("fk_itens_saida_saida1");

                    b.Navigation("Produto");

                    b.Navigation("Saida");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Produto", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.Categoria", "Categoria")
                        .WithMany("Produto")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("fk_produto_categoria1");

                    b.HasOne("ApiHortifruti.Domain.UnidadeMedida", "UnidadeMedida")
                        .WithMany("Produto")
                        .HasForeignKey("UnidadeMedidaId")
                        .IsRequired()
                        .HasConstraintName("fk_produto_unidade_medida1");

                    b.Navigation("Categoria");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Saida", b =>
                {
                    b.HasOne("ApiHortifruti.Domain.MotivoMovimentacao", "MotivoMovimentacao")
                        .WithMany("Saida")
                        .HasForeignKey("MotivoMovimentacaoId")
                        .IsRequired()
                        .HasConstraintName("fk_saida_motivo_movimentacao1");

                    b.Navigation("MotivoMovimentacao");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Categoria", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Entrada", b =>
                {
                    b.Navigation("ItemEntrada");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Fornecedor", b =>
                {
                    b.Navigation("Entrada");

                    b.Navigation("FornecedorProduto");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.MotivoMovimentacao", b =>
                {
                    b.Navigation("Entrada");

                    b.Navigation("Saida");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Produto", b =>
                {
                    b.Navigation("FornecedorProduto");

                    b.Navigation("HistoricoProduto");

                    b.Navigation("ItemEntrada");

                    b.Navigation("ItemSaida");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.Saida", b =>
                {
                    b.Navigation("ItemSaida");
                });

            modelBuilder.Entity("ApiHortifruti.Domain.UnidadeMedida", b =>
                {
                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
